### ISSUE TITLE
"Data" labels are shown on top of sticky filters

### ISSUE THREAD

**Issue by tripu** [w3c/tr-pages#43]
The culprit is a

```css
.data {
  position: relative;
}
```

on [`w3.org/2008/site/css/minimum.css`](https://www.w3.org/2008/site/css/minimum.css), line 156.
